version: "3"
services:
    web:
        labels:
            caddy: doxie.marioslab.io
            caddy.reverse_proxy: "{{upstreams 80}}"
        networks:
            - network
            - reverse_proxy
networks:
    reverse_proxy:
        external:
            name: caddy-network
